# Test your FastAPI endpoints

GET http://127.0.0.1:8082/
Accept: application/json

###

# Test the /admission endpoint with patient type A
POST http://127.0.0.1:8082/admission
Content-Type: application/json
Accept: application/json

{
  "patient_type": "B",
  "admission_date": 1719210000
}

###
